version: "3.2"
services:
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - test

    mongo:
        image: mongo:3.6
        ports:
            - "27017:27017"
        tmpfs:
            - /data/db
        networks:
            - test

    elastic:
        image: elasticsearch:2.4-alpine
        ports:
            - "9200:9200"
        environment:
            - discovery.type=single-node
        tmpfs:
            - /usr/share/elasticsearch/data
        networks:
            - test

networks:
    test:
        driver: bridge
