version: "2.4"
services:
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

    mongo:
        image: mongo:3.6
        ports:
            - "27017:27017"
        tmpfs:
            - /data/db

    elastic:
        image: elasticsearch:2.4-alpine
        ports:
            - "9200:9200"
        environment:
            - discovery.type=single-node
        tmpfs:
            - /usr/share/elasticsearch/data

