#!/usr/bin/env bash

# Install python package dependencie
sudo apt-get -y update
sudo apt-get -y install libxml2-dev libxmlsec1-dev libxmlsec1-openssl

if [ "$SKIP_SERVER_INSTALL" != "true" ]; then
    docker compose up -d
    while ! curl -sfo /dev/null 'http://localhost:9200/'; do echo -n '.' && sleep .5; done
fi
