#!/usr/bin/env bash

# Install python package dependencie
sudo apt-get -y update
sudo apt-get -y install libxml2-dev libxmlsec1-dev libxmlsec1-openssl perl make curl

# Install ExifTool
EXIFTOOL_VERSION="13.32"
curl -LO "https://sourceforge.net/projects/exiftool/files/Image-ExifTool-${EXIFTOOL_VERSION}.tar.gz"
gzip -dc "Image-ExifTool-${EXIFTOOL_VERSION}.tar.gz" | tar -xf -
cd "Image-ExifTool-${EXIFTOOL_VERSION}"
perl Makefile.PL
sudo make install
cd ..

if [ "$SKIP_SERVER_INSTALL" != "true" ]; then
    docker compose up -d
    while ! curl -sfo /dev/null 'http://localhost:9200/'; do echo -n '.' && sleep .5; done
fi
