from typing import Any, Dict, List, TypedDict, Callable, Awaitable, TypeAlias
from enum import Enum, unique

from quart_babel import LazyString
import bson

from .enums import (
    DeskTypeEnum,
    MonitoringTypeEnum,
    MonitoringViewEnum,
    UserTypeEnum,
    PublishState,
    ContentState,
    ContentType,
    TEXT_TYPES,
    MEDIA_TYPES,
    AUTHORING_TYPES,
    PublishOperation,
)
from .desks import DesksResourceModel
from .users import UsersResourceModel, UserTypeEnum
from .vocabularies import VocabulariesResourceModel

from .content_types import ContentTypesResourceModel
from .products import ProductsResource, ProductTypes, ProductFilterType, ProductContentFilter
from .subscribers import SubscribersResource, SubscriberDestination, SubscriberSequenceSettings, SubscriberType
from .subscriber_token import SubscriberToken
from .sequences import SequencesResource
from .content_filters import ContentFilterExpression, ContentFilter, ContentFiltersResource
from .filter_conditions import FilterConditionOperator, FilterConditionFieldParam, FilterConditionsResource
from .publish_queue import PublishQueueState, PublishQueueResource
from .publish import (
    PublishSenderType,
    PublishRequest,
    PublishRequestResponse,
    PublishConsumer,
    PublishExchangeFilter,
    PublishExchange,
    PublishExchangeFactory,
    PublishExchangeFormatter,
    PublishExchangeRouter,
    PublishComponentType,
    ProductItemTestResult,
)
from .archive import ArchiveResourceModel
from .base import ItemOperation, ContentTypes, FORMATS

__all__ = [
    "Id",
    "DeskTypeEnum",
    "MonitoringTypeEnum",
    "MonitoringViewEnum",
    "UserTypeEnum",
    "PublishState",
    "ContentState",
    "ContentType",
    "TEXT_TYPES",
    "MEDIA_TYPES",
    "AUTHORING_TYPES",
    "PublishOperation",
    "UsersResourceModel",
    "UserTypeEnum",
    "DesksResourceModel",
    "VocabulariesResourceModel",
    "ContentTypesResourceModel",
    "ProductsResource",
    "ProductTypes",
    "ProductFilterType",
    "ProductContentFilter",
    "SubscribersResource",
    "SubscriberDestination",
    "SubscriberSequenceSettings",
    "SubscriberType",
    "SubscriberToken",
    "SequencesResource",
    "ContentFilterExpression",
    "ContentFilter",
    "ContentFiltersResource",
    "FilterConditionOperator",
    "FilterConditionFieldParam",
    "FilterConditionsResource",
    "PublishQueueState",
    "PublishQueueResource",
    "PublishSenderType",
    "PublishRequest",
    "PublishRequestResponse",
    "PublishConsumer",
    "PublishExchangeFilter",
    "PublishExchange",
    "PublishExchangeFactory",
    "PublishExchangeFormatter",
    "PublishExchangeRouter",
    "PublishComponentType",
    "ProductItemTestResult",
    "MacroAccessType",
    "MacroActionType",
    "MacroReplaceType",
    "MacroModule",
    "ArchiveResourceModel",
    "ItemOperation",
    "ContentTypes",
    "FORMATS",
]


Id: TypeAlias = str | bson.ObjectId


class WebsocketMessageFilterConditions(TypedDict, total=False):
    include: Dict[str, List[str]]
    exclude: Dict[str, List[str]]


class WebsocketMessageData(TypedDict, total=False):
    event: str
    filters: WebsocketMessageFilterConditions
    extra: Dict[str, Any]
    _created: str  # isoformat
    _process: int


class ItemAuthor(TypedDict):
    uri: str
    parent: str
    name: str
    role: str
    jobtitle: str
    sub_label: str


class Item(TypedDict, total=False):
    headline: str
    slugline: str
    authors: List[ItemAuthor]
    extra: Dict[str, Any]


class UserMandatory(TypedDict):
    email: str
    username: str


class User(UserMandatory, total=False):
    user_preferences: Dict[str, Any]
    needs_activation: bool
    is_enabled: bool
    is_active: bool


@unique
class MacroAccessType(str, Enum):
    FRONTEND = "frontend"
    BACKEND = "backend"


@unique
class MacroActionType(str, Enum):
    DIRECT = "direct"
    INTERACTIVE = "interactive"


@unique
class MacroReplaceType(str, Enum):
    SIMPLE_REPLACE = "simple-replace"
    NO_REPLACE = "no-replace"


class MacroModuleMandatory(TypedDict):
    name: str
    callback: Callable[[dict], Awaitable[dict | tuple[dict, dict]]]
    # callback: Callable[[dict, ...], Awaitable[dict | tuple[dict, dict]]]
    access_type: MacroAccessType
    action_type: MacroActionType
    replace_type: MacroReplaceType


class MacroModule(MacroModuleMandatory, total=False):
    label: str | LazyString
    description: str  # autogenerated from callback docstring
    order: int
    shortcut: str
    from_languages: list[str]
    to_languages: list[str]
    group: str | LazyString
