name: "Lint"

on: [push, pull_request]

jobs:
  black:
    strategy:
      matrix:
        python-version: ['3.12']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.0
    - uses: actions/setup-python@v6
      with:
        cache: 'pip'
        python-version: ${{ matrix.python-version }}
    - run: pip install -Ur dev-requirements.txt
    - run: black --check .

  flake8:
    strategy:
      matrix:
        python-version: ['3.12']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.0
    - uses: actions/setup-python@v6
      with:
        cache: 'pip'
        python-version: ${{ matrix.python-version }}
    - run: pip install -Ur dev-requirements.txt
    - run: flake8

  mypy:
    strategy:
      matrix:
        python-version: ['3.12']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.0
    - uses: actions/setup-python@v6
      with:
        cache: 'pip'
        python-version: ${{ matrix.python-version }}
    - run: pip install -Ur dev-requirements.txt
    - run: mypy .
