name: "Test"

on: [push, pull_request]

jobs:
  pytest:
    env:
      ELASTIC_CLIENT_APIVERSIONING: 1

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            python-version: '3.12'
            elastic: '7.17.29'
          - os: ubuntu-24.04
            python-version: '3.12'
            elastic: '8.19.6'

    runs-on: ${{ matrix.os }}

    services:
      redis:
        image: redis:8
        ports:
            - "6379:6379"

      mongo:
        image: mongo:8
        ports:
            - "27017:27017"

      elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:${{ matrix.elastic }}
        ports:
            - "9200:9200"
        env:
            discovery.type: single-node
            xpack.security.enabled: false

    steps:
    - uses: actions/checkout@v7.0.0
    - uses: actions/setup-python@v6.3.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - run: ./scripts/tests_setup
      env:
        SKIP_SERVER_INSTALL: true

    - run: pip install -Ur dev-requirements.txt
    - run: pytest --log-level=ERROR --disable-warnings tests/core
    - run: pytest --log-level=ERROR --disable-warnings --ignore=tests/core

  pip-compile:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v7.0.0
    - uses: actions/setup-python@v6.3.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - run: pip install -Ur dev-requirements.txt
    - run: pip-compile -U setup.py

  behave:
    env:
      ELASTIC_CLIENT_APIVERSIONING: 1

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            python-version: '3.12'
            elastic: '7.17.29'
          - os: ubuntu-24.04
            python-version: '3.12'
            elastic: '8.19.6'

    runs-on: ${{ matrix.os }}

    services:
      redis:
        image: redis:8
        ports:
            - "6379:6379"

      mongo:
        image: mongo:8
        ports:
            - "27017:27017"

      elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:${{ matrix.elastic }}
        ports:
            - "9200:9200"
        env:
            discovery.type: single-node
            xpack.security.enabled: false

    steps:
    - uses: actions/checkout@v7.0.0

    - uses: actions/setup-python@v6.3.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - run: ./scripts/tests_setup
      env: 
        SKIP_SERVER_INSTALL: true
    - run: pip install -Ur dev-requirements.txt

    - run: behave --tags=-sams --format progress2 --logging-level=ERROR

  behave-sams:
    if: ${{ false }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            python-version: '3.12'

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v7.0.0

    - uses: actions/setup-python@v6.3.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - run: ./scripts/tests_setup
    - run: ./scripts/install-start-sams

    - run: pip install -Ur dev-requirements.txt

    - run: behave --tags=sams --format progress2 --logging-level=ERROR

  prodapi:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            python-version: '3.12'

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v7.0.0

    - uses: actions/setup-python@v6.3.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - run: ./scripts/tests_setup
    - run: pip install -Ur dev-requirements.txt

    - run: pytest --disable-warnings prod_api

  macos-install:
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-latest']
        python-version: ['3.12']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v7.0.0

    - uses: actions/setup-python@v6.3.0
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install -Ur dev-requirements.txt
